### ISSUE TITLE
mlrAnatDB Screenshots Don't Work w/ Multiple pRF Analysis

### ISSUE THREAD

**Issue by dbirman** [justingardner/mrTools#30]
In session s031020150815 there are two pRF analyses: pRF_left and pRF_right for each hemisphere separately. When "Add ROIs to AnatDB" runs it fails to load the correct analysis during the screenshotting, causing one screenshot to be empty. See: http://gru.stanford.edu/doku.php/mlranatdb/s0310.

**Comment by justingardner** [comment]
Right. I am thinking of just leaving it with this behavior for two reasons. One is that pRF analyses should no longer be run separately for one hemisphere at a time - I did a bunch of work on the pRF code when JouJou was running it so that you can continue analyses - so now the preferred way of running say left then right will create a single analysis instead of splitting into two - which was inconvenient and annoying anyway. Second, I think if we have too many decisions to make when exporting ROIs it will get tedious, so want to avoid to much selection of stuff like what analysis and overlay you want to display - the assumption is that you want to display with the current analysis and overlay settings. 

If you do need to add ROIs with different analyses, the best way to do it would be to export twice. In between you can set the analysis and overlay. 

If this is too inconvenient for usual case scenarios, I'll fix it. Let me know...

**Comment by dbirman** [comment]
Oh didn't realize the pRF code was fixed now, so if I run a second analysis and say "merge" it will work correctly?

**Comment by justingardner** [comment]
Yep. Merge works now. Also, if you run pRF from the menu when one is loaded, it will ask you if you want to continue the last one - just giving you options to select the new base anatomy or roi you want to restrict with...

**Comment by dbirman** [comment]
Cool! Thanks
